### ISSUE TITLE
POSTCODE WRONG CREDENTIALS

### ISSUE THREAD

**Issue by Somnath8800** [praveenpal12345/Project-Practice-Lab#225]
woocommerce version:5.7.2
Php version:not available
### commit id-bb094efc9a243f693572416eb0bd5ee67a216b56
Mode:Production/Maintenance

### Description
POSTCODE is getting saved with invalid credentials

### Steps to reproduce
Step1: open admin dashboard>point of sales>settings
step2:go to customer settings and enter invalid credentials of postcode such as alphanumeric and click on update customer

### Expected result
validation message must be recieved as 'invalid credentials'

### Actual result
details gets saved
![POSTCODE](https://user-images.githubusercontent.com/89394178/132207989-7eb4ba1b-e78b-4c8c-af65-877621678b48.png)

**Comment by praveenpal12345** [comment]
- @praveenpal12345 It is fixed now

**Comment by praveenpal12345** [comment]
- It is working fine
